# render.yaml
services:
  # This is your Flask web service
  - type: web
    name: skillswap-api # Choose a name for your API service
    env: python
    repo: https://github.com/draron-dare-045/SKILL_SWAP # CHANGE THIS
    plan: free # or your desired plan
    branch: main # or your default branch
    rootDir: backend # Tells Render to look inside the 'backend' folder
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade && flask seed"
    startCommand: "gunicorn --workers 3 --bind 0.0.0.0:$PORT 'app:create_app()'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillswap-db # Must match the database name below
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false # Set this in the dashboard for security
      - key: PYTHON_VERSION
        value: 3.11 # Or your Python version

  # This is your PostgreSQL database
  - type: psql
    name: skillswap-db # Choose a name for your database
    plan: free # or your desired plan