# backend/render.yaml - A Blueprint for deploying the SkillSwap API and Database on Render

services:
  # ----------------- #
  # Flask API Service #
  # ----------------- #
  - type: web
    name: skillswap-api
    env: python
    repo: https://github.com/draron-dare-045/SKILL_SWAP
    branch: main
    # This tells Render that your Flask app lives in the 'backend' subfolder
    rootDir: backend
    
    # --- Build & Deploy Configuration ---
    # Render is already inside the 'backend' folder, so it finds requirements.txt here.
    buildCommand: "pip install -r requirements.txt"
    # These commands also run from inside the 'backend' folder and will work correctly.
    preDeployCommand: "flask db upgrade && flask seed"
    startCommand: "gunicorn --workers 3 --bind 0.0.0.0:$PORT 'app:create_app()'"
    
    # --- Environment Variables ---
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: skillswap-database
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

  # -------------------- #
  # PostgreSQL Database  #
  # -------------------- #
  - type: psql
    name: skillswap-database
    plan: free